name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Package installation
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint
        
      - name: Testing
        run: pnpm test

      - name: Build production
        run: pnpm run build:prod
        
      
          