name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Package installation
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint
        
      - name: Testing
        run: pnpm test

      - name: Build production
        run: pnpm run build:prod
        
      - name: Coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GOOPUBTAG_COVERAGE_BADGE }}
          gistID: 6098142efd5a281865b461a4c89acd8e
          filename: gpt_coverage_badge.json
          label: Hello
          message: World
          color: orange
        
      
          